### ISSUE TITLE
Could you make a README.md file?

### ISSUE THREAD

**Issue by DavidNexuss** [raeleus/bobbybird#1]
I was bored searching things un GitHub when I found this prohect. I'm interested un it, and it would be great a file explaining what is about.

Is 2D platformer maybe?
Seems very interesting.

**Comment by raeleus** [comment]
This shouldn't be of interest to anyone. It's just a small Flappy Bird clone that I'll be using as a teaching tool for children. I don't think anyone else will have a use for it though. Thanks for your inquiry.
